/*
 * Selling Partner API for Finances
 *
 * The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model/finances/v0;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ListFinancialEventGroupsPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListFinancialEventGroupsPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListFinancialEventGroupsPayload
        //private ListFinancialEventGroupsPayload instance;

        public ListFinancialEventGroupsPayloadTests()
        {
            // TODO uncomment below to create an instance of ListFinancialEventGroupsPayload
            //instance = new ListFinancialEventGroupsPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListFinancialEventGroupsPayload
        /// </summary>
        [Fact]
        public void ListFinancialEventGroupsPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListFinancialEventGroupsPayload
            //Assert.IsType<ListFinancialEventGroupsPayload>(instance);
        }

        /// <summary>
        /// Test the property 'NextToken'
        /// </summary>
        [Fact]
        public void NextTokenTest()
        {
            // TODO unit test for the property 'NextToken'
        }

        /// <summary>
        /// Test the property 'FinancialEventGroupList'
        /// </summary>
        [Fact]
        public void FinancialEventGroupListTest()
        {
            // TODO unit test for the property 'FinancialEventGroupList'
        }
    }
}
