/*
 * The Selling Partner API for Automotive.
 *
 * The Selling Partner API for Automotive provides programmatic access to information needed by selling partners to provide compatibility information about their listed products.
 *
 * The version of the OpenAPI document: 2024-11-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Amazon.SellingPartnerAPI.SDK.Client;
using Amazon.SellingPartnerAPI.SDK.Api/vehicles/v2024_11_01;
using Amazon.SellingPartnerAPI.SDK.Model/vehicles/v2024_11_01;

namespace Amazon.SellingPartnerAPI.SDK.Test
{
    /// <summary>
    ///  Class for testing AutomotiveApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AutomotiveApiTests
    {
        private AutomotiveApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to initialize instance for testing
            //instance = new AutomotiveApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AutomotiveApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AutomotiveApi
            //Assert.IsInstanceOfType(typeof(AutomotiveApi), instance, "instance is a AutomotiveApi");
        }

        
        /// <summary>
        /// Test GetVehicles_0
        /// </summary>
        [Test]
        public void GetVehicles_0Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string marketplaceId = null;
            //string vehicleType = null;
            //string? pageToken = null;
            //string? updatedAfter = null;
            //var response = instance.GetVehicles_0(marketplaceIdvehicleTypepageTokenupdatedAfter);
            //Assert.IsInstanceOf<VehiclesResponse> (response, "response is VehiclesResponse");
        }
        
    }

}
