/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model/merchantFulfillment/v0;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AvailableCarrierWillPickUpOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailableCarrierWillPickUpOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailableCarrierWillPickUpOption
        //private AvailableCarrierWillPickUpOption instance;

        public AvailableCarrierWillPickUpOptionTests()
        {
            // TODO uncomment below to create an instance of AvailableCarrierWillPickUpOption
            //instance = new AvailableCarrierWillPickUpOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailableCarrierWillPickUpOption
        /// </summary>
        [Fact]
        public void AvailableCarrierWillPickUpOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvailableCarrierWillPickUpOption
            //Assert.IsType<AvailableCarrierWillPickUpOption>(instance);
        }

        /// <summary>
        /// Test the property 'CarrierWillPickUpOption'
        /// </summary>
        [Fact]
        public void CarrierWillPickUpOptionTest()
        {
            // TODO unit test for the property 'CarrierWillPickUpOption'
        }

        /// <summary>
        /// Test the property 'Charge'
        /// </summary>
        [Fact]
        public void ChargeTest()
        {
            // TODO unit test for the property 'Charge'
        }
    }
}
