/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model/merchantFulfillment/v0;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing HazmatType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HazmatTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HazmatType
        //private HazmatType instance;

        public HazmatTypeTests()
        {
            // TODO uncomment below to create an instance of HazmatType
            //instance = new HazmatType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HazmatType
        /// </summary>
        [Fact]
        public void HazmatTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" HazmatType
            //Assert.IsType<HazmatType>(instance);
        }
    }
}
