/*
 * Selling Partner API for Merchant Fulfillment
 *
 * With the Selling Partner API for Merchant Fulfillment, you can build applications that sellers can use to purchase shipping for non-Prime and Prime orders using Amazon's Buy Shipping Services.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model/merchantFulfillment/v0;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing LabelFormatOptionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabelFormatOptionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LabelFormatOptionRequest
        //private LabelFormatOptionRequest instance;

        public LabelFormatOptionRequestTests()
        {
            // TODO uncomment below to create an instance of LabelFormatOptionRequest
            //instance = new LabelFormatOptionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LabelFormatOptionRequest
        /// </summary>
        [Fact]
        public void LabelFormatOptionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" LabelFormatOptionRequest
            //Assert.IsType<LabelFormatOptionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'IncludePackingSlipWithLabel'
        /// </summary>
        [Fact]
        public void IncludePackingSlipWithLabelTest()
        {
            // TODO unit test for the property 'IncludePackingSlipWithLabel'
        }
    }
}
