/*
 * Selling Partner API for Retail Procurement Orders
 *
 * The Selling Partner API for Retail Procurement Orders provides programmatic access to vendor orders data.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model.vendor.orders.v1;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing PartyIdentification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PartyIdentificationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PartyIdentification
        //private PartyIdentification instance;

        public PartyIdentificationTests()
        {
            // TODO uncomment below to create an instance of PartyIdentification
            //instance = new PartyIdentification();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PartyIdentification
        /// </summary>
        [Fact]
        public void PartyIdentificationInstanceTest()
        {
            // TODO uncomment below to test "IsType" PartyIdentification
            //Assert.IsType<PartyIdentification>(instance);
        }

        /// <summary>
        /// Test the property 'PartyId'
        /// </summary>
        [Fact]
        public void PartyIdTest()
        {
            // TODO unit test for the property 'PartyId'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'TaxInfo'
        /// </summary>
        [Fact]
        public void TaxInfoTest()
        {
            // TODO unit test for the property 'TaxInfo'
        }
    }
}
