/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model.vendor.shipments.v1;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing CartonReferenceDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartonReferenceDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartonReferenceDetails
        //private CartonReferenceDetails instance;

        public CartonReferenceDetailsTests()
        {
            // TODO uncomment below to create an instance of CartonReferenceDetails
            //instance = new CartonReferenceDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartonReferenceDetails
        /// </summary>
        [Fact]
        public void CartonReferenceDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartonReferenceDetails
            //Assert.IsType<CartonReferenceDetails>(instance);
        }

        /// <summary>
        /// Test the property 'CartonCount'
        /// </summary>
        [Fact]
        public void CartonCountTest()
        {
            // TODO unit test for the property 'CartonCount'
        }

        /// <summary>
        /// Test the property 'CartonReferenceNumbers'
        /// </summary>
        [Fact]
        public void CartonReferenceNumbersTest()
        {
            // TODO unit test for the property 'CartonReferenceNumbers'
        }
    }
}
