/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model.vendor.shipments.v1;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing PurchaseOrders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PurchaseOrdersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PurchaseOrders
        //private PurchaseOrders instance;

        public PurchaseOrdersTests()
        {
            // TODO uncomment below to create an instance of PurchaseOrders
            //instance = new PurchaseOrders();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PurchaseOrders
        /// </summary>
        [Fact]
        public void PurchaseOrdersInstanceTest()
        {
            // TODO uncomment below to test "IsType" PurchaseOrders
            //Assert.IsType<PurchaseOrders>(instance);
        }

        /// <summary>
        /// Test the property 'PurchaseOrderNumber'
        /// </summary>
        [Fact]
        public void PurchaseOrderNumberTest()
        {
            // TODO unit test for the property 'PurchaseOrderNumber'
        }

        /// <summary>
        /// Test the property 'PurchaseOrderDate'
        /// </summary>
        [Fact]
        public void PurchaseOrderDateTest()
        {
            // TODO unit test for the property 'PurchaseOrderDate'
        }

        /// <summary>
        /// Test the property 'ShipWindow'
        /// </summary>
        [Fact]
        public void ShipWindowTest()
        {
            // TODO unit test for the property 'ShipWindow'
        }

        /// <summary>
        /// Test the property 'Items'
        /// </summary>
        [Fact]
        public void ItemsTest()
        {
            // TODO unit test for the property 'Items'
        }
    }
}
