/*
 * Selling Partner API for Retail Procurement Shipments
 *
 * The Selling Partner API for Retail Procurement Shipments provides programmatic access to retail shipping data for vendors.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model.vendor.shipments.v1;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing SubmitShipments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmitShipmentsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmitShipments
        //private SubmitShipments instance;

        public SubmitShipmentsTests()
        {
            // TODO uncomment below to create an instance of SubmitShipments
            //instance = new SubmitShipments();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmitShipments
        /// </summary>
        [Fact]
        public void SubmitShipmentsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmitShipments
            //Assert.IsType<SubmitShipments>(instance);
        }

        /// <summary>
        /// Test the property 'Shipments'
        /// </summary>
        [Fact]
        public void ShipmentsTest()
        {
            // TODO unit test for the property 'Shipments'
        }
    }
}
