/*
 * Selling Partner API for Product Fees
 *
 * The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.
 *
 * The version of the OpenAPI document: v0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Amazon.SellingPartnerAPI.SDK.Client;
using Amazon.SellingPartnerAPI.SDK.Api/productFees/v0;
using Amazon.SellingPartnerAPI.SDK.Model/productFees/v0;

namespace Amazon.SellingPartnerAPI.SDK.Test
{
    /// <summary>
    ///  Class for testing FeesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FeesApiTests
    {
        private FeesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to initialize instance for testing
            //instance = new FeesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FeesApi
            //Assert.IsInstanceOfType(typeof(FeesApi), instance, "instance is a FeesApi");
        }

        
        /// <summary>
        /// Test GetMyFeesEstimateForASIN
        /// </summary>
        [Test]
        public void GetMyFeesEstimateForASINTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string asin = null;
            //GetMyFeesEstimateRequest body = null;
            //var response = instance.GetMyFeesEstimateForASIN(asinbody);
            //Assert.IsInstanceOf<GetMyFeesEstimateResponse> (response, "response is GetMyFeesEstimateResponse");
        }
        
        /// <summary>
        /// Test GetMyFeesEstimateForSKU
        /// </summary>
        [Test]
        public void GetMyFeesEstimateForSKUTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sellerSKU = null;
            //GetMyFeesEstimateRequest body = null;
            //var response = instance.GetMyFeesEstimateForSKU(sellerSKUbody);
            //Assert.IsInstanceOf<GetMyFeesEstimateResponse> (response, "response is GetMyFeesEstimateResponse");
        }
        
        /// <summary>
        /// Test GetMyFeesEstimates
        /// </summary>
        [Test]
        public void GetMyFeesEstimatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<FeesEstimateByIdRequest> body = null;
            //var response = instance.GetMyFeesEstimates(body);
            //Assert.IsInstanceOf<List<FeesEstimateResult>> (response, "response is List<FeesEstimateResult>");
        }
        
    }

}
