/*
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model.supplySources.v2020_07_01;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing SupplySourceConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SupplySourceConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SupplySourceConfiguration
        //private SupplySourceConfiguration instance;

        public SupplySourceConfigurationTests()
        {
            // TODO uncomment below to create an instance of SupplySourceConfiguration
            //instance = new SupplySourceConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SupplySourceConfiguration
        /// </summary>
        [Fact]
        public void SupplySourceConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" SupplySourceConfiguration
            //Assert.IsType<SupplySourceConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'OperationalConfiguration'
        /// </summary>
        [Fact]
        public void OperationalConfigurationTest()
        {
            // TODO unit test for the property 'OperationalConfiguration'
        }

        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
    }
}
