/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model/catalogItems/v2022_04_01;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ItemProductTypeByMarketplace
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemProductTypeByMarketplaceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemProductTypeByMarketplace
        //private ItemProductTypeByMarketplace instance;

        public ItemProductTypeByMarketplaceTests()
        {
            // TODO uncomment below to create an instance of ItemProductTypeByMarketplace
            //instance = new ItemProductTypeByMarketplace();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemProductTypeByMarketplace
        /// </summary>
        [Fact]
        public void ItemProductTypeByMarketplaceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemProductTypeByMarketplace
            //Assert.IsType<ItemProductTypeByMarketplace>(instance);
        }

        /// <summary>
        /// Test the property 'MarketplaceId'
        /// </summary>
        [Fact]
        public void MarketplaceIdTest()
        {
            // TODO unit test for the property 'MarketplaceId'
        }

        /// <summary>
        /// Test the property 'ProductType'
        /// </summary>
        [Fact]
        public void ProductTypeTest()
        {
            // TODO unit test for the property 'ProductType'
        }
    }
}
