/*
 * Selling Partner API for Catalog Items
 *
 * Use the Selling Partner API for Catalog Items to retrieve information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * The version of the OpenAPI document: 2022-04-01
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPI.SDK.Model.catalogItems.v2022_04_01;
using Amazon.SellingPartnerAPI.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPI.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing BrandRefinement
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BrandRefinementTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BrandRefinement
        //private BrandRefinement instance;

        public BrandRefinementTests()
        {
            // TODO uncomment below to create an instance of BrandRefinement
            //instance = new BrandRefinement();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrandRefinement
        /// </summary>
        [Fact]
        public void BrandRefinementInstanceTest()
        {
            // TODO uncomment below to test "IsType" BrandRefinement
            //Assert.IsType<BrandRefinement>(instance);
        }

        /// <summary>
        /// Test the property 'NumberOfResults'
        /// </summary>
        [Fact]
        public void NumberOfResultsTest()
        {
            // TODO unit test for the property 'NumberOfResults'
        }

        /// <summary>
        /// Test the property 'BrandName'
        /// </summary>
        [Fact]
        public void BrandNameTest()
        {
            // TODO unit test for the property 'BrandName'
        }
    }
}
